### ISSUE TITLE
The documents,dekstop and downloads folder can not be accessed in Jupyterlab MacOS Catalina

### ISSUE THREAD

**Issue by Soheila19** [BME1478H/Fall2020class#244]
Hey Folks, 
This is a comment rather than a question. I realized that when I open Jupyter lab on Mac, id doesnt allow me open any notebooks from certain folders. I googled and realized that the latest update (MAcOs Catalina) does not allow jupyter lab access desktop, documents and doenloads. For more infor foolow this github post. 

Cheers, 
Soheila https://github.com/ContinuumIO/anaconda-issues/issues/11350

**Comment by joelostblom** [comment]
Thanks for sharing so that others can see your post!

Does it work for you if you grant full disk access to python and the jupyter apps as per [the screenshot in this post](https://github.com/ContinuumIO/anaconda-issues/issues/11387#issuecomment-581243487)?
