### ISSUE TITLE
A10 last question

### ISSUE THREAD

**Issue by minyaowang0810** [BME1478H/Fall2020class#256]
<img width="824" alt="Screen Shot 2020-03-28 at 3 24 39 PM" src="https://user-images.githubusercontent.com/59656499/77831890-3e78c280-7108-11ea-8cdd-92699d052b7d.png">

Hi, I don't know why the prediction label is not showing in the graph. Thanks

**Comment by linamnt** [comment]
Hi good question, you would need add a line with `plt.legend()` as the last line to actually invoke the legend with both. It seems `seaborn` plots automatically show a legend if a label is given, but using plt.scatter does not (by default) until you call `plt.legend()`. It would have worked without calling the legend if we just passed the same data to another `sns.scatterplot()` for the second plot, but we specifically asked for `plt.scatter()`. 

Either way, we didn't explicitly explain this in the lecture material, so I will add a note to the assignment.
