### ISSUE TITLE
Assignment 10 Task 3 

### ISSUE THREAD

**Issue by Brendannigel** [BME1478H/Fall2020class#260]
```python
y = world_data_2014['child_mortality']
x = world_data_2014['income']
x_new = sm.add_constant(x)
le_model = sm.GLM(y, x_new, family=sm.families.Gaussian(link=sm.families.links.log()))

le_results = le_model.fit()


# do not change the code below()
print(le_results.summary())`
```

![image](https://user-images.githubusercontent.com/59632050/78460606-2ec12700-7690-11ea-8cd8-5e41b79e3c70.png)

Hi I was wondering if this code was correct since I was having trouble with the sm.add_constant section of this question. I got the correct result I think but I am not sure if in the sns.scatterplot and plt.scatter if I would have to call x as x_new as per my code in the previous cell or do I just leave it as x.

Thanks

**Comment by joelostblom** [comment]
That plot looks good to me :+1: And defining a new x variable as you did is fine.

But remember that when you call `sns.scatterplot`, you should supply the column **names** of the data frame **as strings**. You are currently providing it with two separate pandas Series (x and y), which works here but could give you headaches down the road so make sure to use strings of the column names instead.
