### ISSUE TITLE
A11 Q2: Run test and plots on single year of data

### ISSUE THREAD

**Issue by mwychan-BME** [BME1478H/Fall2020class#265]
For Q2, we are given `new_world_data` that includes new columns and removal of old columns. The question then asks to do a regression and generate the scatterplots comparing predicted and actual. 

Are we supposed to do the regression and plots on a single year (e.g. 2005)? It is not in the step-by-step for column dropping and cleanup, but the scatterplots end up looking weird if all the years are retained.

**Comment by joelostblom** [comment]
You're right that the scatterplot will look a bit odd in the sense that you can see the individual trajectories of individual countries over time. As you said, an alternative here could have been to e.g. look at years separately or facet by decades, but we decided not to include that in this task.
