### ISSUE TITLE
A 11 Q 2D

### ISSUE THREAD

**Issue by MT-droid** [BME1478H/Fall2020class#272]
Hi there, for this question, after creating 2 scatterplots I am not sure what you mean by  "the second should use the values in results.predict()", I used the following code and got a single scatterplot that is shaped in a line ascending from left to right and am unsure if this is what was meant?

ypred = results.predict(education_clean.education_gender_ratio) # predicted from our results
sns.scatterplot (x = 'education_gender_ratio', y = ypred, data = education_clean, ax = ax4)

any help understanding this question would be appreciated! Thank you

**Comment by joelostblom** [comment]
Conceptually this makes sense, the predictions are from a *linear* model of this data so they should be in a straight line. So you should have one scatterplot with your messy raw data and one with the linear predictions.
