### ISSUE TITLE
A11 Q2D

### ISSUE THREAD

**Issue by Juniperberry-git** [BME1478H/Fall2020class#273]
I tried to plot the 2 graphs, but the predicted values looks weird....is this right
<img width="796" alt="Annotation 2020-04-12 180754" src="https://user-images.githubusercontent.com/60361821/79081175-e5ed1c00-7ce8-11ea-8e5d-5375171bde87.png">

**Comment by joelostblom** [comment]
Overall this makes sense, you have your messy raw data and then a *linear* model of this data. Make sure to double check how you created the `education_gender_ratio` variable with the instructions in 2a.

**Comment by Brendannigel** [comment]
I thought we are supposed to plot two graphs in one like this

![image](https://user-images.githubusercontent.com/59632050/79081893-6c0c6100-7cef-11ea-86db-da39e347a4c8.png)
 that what the email on of the TAs sent to me

**Comment by joelostblom** [comment]
We will accept either solution. In terms of which is more informative, I think plotting both the raw data and the predictions in the same axis makes it easier to compare them.

**Comment by Brendannigel** [comment]
okay thank you
