### ISSUE TITLE
A11 Q4

### ISSUE THREAD

**Issue by Juniperberry-git** [BME1478H/Fall2020class#274]
When I try to run the predictions for my Decision Tree Regressor I get an error regarding an error due to NA values in my X data set, and when indeed further up when we converted some values into 1 or 0, there were a lot of NA values, how do I fix this?
<img width="630" alt="Annotation 1" src="https://user-images.githubusercontent.com/60361821/79082279-8ac02700-7cf2-11ea-873c-cf38f4652e8f.png">
<img width="587" alt="Annotation 2" src="https://user-images.githubusercontent.com/60361821/79082281-8c89ea80-7cf2-11ea-8857-f1dba74e1033.png">
<img width="560" alt="Annotation 3" src="https://user-images.githubusercontent.com/60361821/79082282-8dbb1780-7cf2-11ea-93ee-5009c8b171a7.png">

**Comment by joelostblom** [comment]
Did you use `dropna()` in 3a?

> Then append .dropna(how=any, axis=0) to this line of code to clean our data and remove rows which have a null value in any of the columns. (0.5 marks)

**Comment by Juniperberry-git** [comment]
Ah, yes you're right I entered the wrong data frame for my decision tree, thanks!
