### ISSUE TITLE
Assignment 2 Clarifications (Fall 2020)

### ISSUE THREAD

**Issue by constructor-s** [BME1478H/Fall2020class#275]
Hello course instructors, 

I hope this is the right place to submit questions regarding assignments of BME1478H during Fall 2020. I have a few detailed questions regarding the specification of assignment 2. 

1. In Question 1: When copying to `DATA_ANALYSIS`, since many `.jpg` images in the different folders have the same file basename (e.g. `20180204-01/1.jpg  20180220-01/1.jpg  20180220-02/1.jpg  20180310-01/1.jpg  20180310-02/1.jpg  20180405-01/1.jpg  20180511-01/1.jpg`), are we supposed to 
A) preserve the directory structure when copying over (e.g. resulting in `IMAGES/20180204-01/1.jpg  IMAGES/20180220-01/1.jpg  IMAGES/20180220-02/1.jpg  IMAGES/20180310-01/1.jpg  IMAGES/20180310-02/1.jpg  IMAGES/20180405-01/1.jpg  IMAGES/20180511-01/1.jpg`), or 
B) somehow copy and assign unique names to each file, or 
C) overwrite files with the same name? (e.g. resulting in only one `IMAGES/1.jpg`)
I assume the same specification will apply for the second part, `DATA_ANALYSIS` folder? 

1. For Question 2: The filename for the notes are not consistent. In particular, even though the assignment says "one **txt** file in which she writes notes during each experiment", the actual file extensions vary from `.txt`, `.ext`, and even one without an extension, all of which are plain text files. Should we assume that any filename that contains the substring "note" (i.e. glob `*note*`) are notes, or assume any `.txt` files (i.e. `*.txt`) are notes?

1. For Question 2: Can we assume that all demographic data are consistently named `info.csv`, or do we need to glob `*.csv`?

1. For Questions 2, 3, and 4: Are these operations supposed to be operated upon the original directories  (i.e. `./20180204-01/  ./20180220-01/  ./20180220-02/  ./20180310-01/  ./20180310-02/  ./20180405-01/  ./20180511-01/`) or the new `./IMAGES/` and `./DATA_ANALYSIS/`?

1. For Question 4: Does the backup have the same directory structure as the original? Can we use `diff` or `git diff` (`diff` is installed by default in most UNIX/Linux distributions, and also available in Windows Git Bash. Even if `diff` is not available, I guess `git` may assumed to be available in PATH for this course)? As follow up to #24, does it matter if we compare not only the file paths but also the content (which is trivial with `diff`)? Is there any requirements on the output format - just human readable? When writing out the command, what should we specify as the path of the "backup" on the "external hard drive"? Is there an example of a "backup" for us to test the command against?

Thank you!

**Comment by RayNele** [comment]
Hi Bill,

Thanks for using the appropriate method for bringing up your concerns, as well as sifting through previous issues before posting your question. 

1. preserve the directory structure (option A)
2. either of these is okay. 
3. ```*.csv``` is probably a better bet here. 
4. Do this on the original directory
5. The backup is a literal copy. Anything that doesn't require you to install through your package manager is fair game for this assignment. As per #24, you are NOT REQUIRED to compare the content. If your script does so, more points to you (not really you cannot get more than full marks for this assignment). You can just make a placeholder path (or whatever path you tested it with). As for an example backup, feel free to make one yourself. ```cp``` the entire folder, run your bash script, then ```rm``` one of the files and try it again.

**Comment by constructor-s** [comment]
> Hi Bill,
> 
> Thanks for using the appropriate method for bringing up your concerns, as well as sifting through previous issues before posting your question. 
> 
> 1. preserve the directory structure (option A)
> 2. either of these is okay. 
> 3. ```*.csv``` is probably a better bet here. 
> 4. Do this on the original directory
> 5. The backup is a literal copy. Anything that doesn't require you to install through your package manager is fair game for this assignment. As per #24, you are NOT REQUIRED to compare the content. If your script does so, more points to you (not really you cannot get more than full marks for this assignment). You can just make a placeholder path (or whatever path you tested it with). As for an example backup, feel free to make one yourself. ```cp``` the entire folder, run your bash script, then ```rm``` one of the files and try it again. 
> 

Hi @RayNele, 

Thanks for your very prompt and useful reply! 

Just so I get a definitive answer to avoid any ambiguities down the road, **may I assume `diff` is in PATH** for the purpose of this assignment? I believe this is true for default installation (without additional install with package manager) of macOS, Ubuntu, and also Bash Shell installed by Git for Windows as instructed by the course instructions. 

Thanks! 

Bill

**Comment by RayNele** [comment]
Yes you may. It is part of the default installation for every system I've
ever used.
