### ISSUE TITLE
Submission Format for Assignment #2

### ISSUE THREAD

**Issue by MatteoBomben** [BME1478H/Fall2020class#276]
Hello,

I just wanted to double check how we are supposed to submit our code for assignment #2. 

Based on the guidelines on Quercus, we are supposed to submit the assignment as a PDF. As such, I copied my commands into a word document (underneath headings indicating which question I was answering) and then exported this as a PDF.

Is this acceptable or is there a special program we should be using to prepare our submissions?

Thanks,

Matteo

**Comment by constructor-s** [comment]
Assuming nothing has changed between semesters, see: https://github.com/BME1478H/Fall2020class/issues/7

**Comment by RayNele** [comment]
Thanks bill, that's correct.

**Comment by MatteoBomben** [comment]
Thanks so much for the help
