### ISSUE TITLE
A2Q2 Loop not outputting correctly 

### ISSUE THREAD

**Issue by maryammahjoob** [BME1478H/Fall2020class#278]
Hello!

My question is in regards to assignment 2 question 2. 

My approach to assignment 2 q2 is creating a loop with if statements. I used the wc command to create the boolean conditions for the if statement by creating a variable which would equal the integer value of the wc command. When I run the following code - I get a strange output. I tried troubleshooting my code for hours and didn't get any luck to finding out the issue - I am wondering if anyone can help me figure out whats wrong! 

The code is below, and I run it when I am in the working directory of assignment-data. 

```
DIR=$(ls);
for D in $DIR;
do var=$(find . -type f -name *.txt| wc -l);
if [ $var=1 ];
then echo "$D not missing note file";
else echo "$D missing note file";
fi;
done
```

Thank you in advance for your time! The output I am getting for the code is below: 

0 not missing note file
0] not missing note file
0]] not missing note file
20180204-01 not missing note file
20180220-01 not missing note file
20180220-02 not missing note file
20180310-01 not missing note file
20180310-02 not missing note file
20180405-01 not missing note file
20180511-01 not missing note file

**Comment by RayNele** [comment]
`find . -type f -name *.txt| wc -l` 

the `.` in this command tells bash to look in the current directory. Find also looks in its subdirectories. if you `$echo var` you'll see a number far greater than 1 since it finds all the *.txt in all the directories and subdirectories.

additionally, you need a space between the variable and = sign. It's just executing whatever you have under `then` right now and not making a boolean comparison. 
`[ $var = 1 ]


You'll find that [ $var=1 ] is

**Comment by maryammahjoob** [comment]
Hi Ray, thank you so much for your advice! I removed the `.` so Find can look in subdirectories. Additionally, I fixed the "var" and "=" sign spacing - unfortunately it is still not working. I made var=0 since if there is no .txt file, wc -l would have 0 as the output. Then I made my code that if wc -l = 0, the if statement would output "$D missing note file". 

This is the code `for D in $DIR; do var=$(find -type f -name *.txt| wc -l); if [ $var = 0 ]; then echo "$D missing note file"; else echo "$D missing not note file"; fi; done`

This is the output: 
`find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
0 missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
0] missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
0]] missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180204-01 missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180220-01 missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180220-02 missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180310-01 missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180310-02 missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180405-01 missing note file
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180511-01 missing note file`

**Comment by RayNele** [comment]
>I removed the . so Find can look in subdirectories.

That's not what I meant there. You're looping the exact same command 10 times . Lets run through the code line by line.

so the first iteration of your loop, `for folder1; do var=$(find . -type f -name *.txt| wc -l)`
here you are assigning `var` to the output of `find . -type f -name *.txt| wc -l` your find looks in the its directories and subdirectories so you are finding ALL text files that exist in your directory (which is like 7 or 8). So in this case `var=8` 

okay lets move onto the next iteration. `for folder2; do var=$(find . -type f -name *.txt| wc -l)`
do you notice what's wrong here now? It's the same variable assignment. You assigned `var=8` AGAIN. Something has to change in this line of code referencing the folder you want to be finding things in, or it will continue to assign the same value every time. Removing the . doesn't change the fact that you are repeating the same command in every single iteration of your for loop.


I can give you another example in pseudocode. Say the question asks you to multiply every value in a list (1 to 10) by 2. Your current approach would be like this:

`for value in list, print 1 times 2.`

If you run that you would get the output 2,2,2,2,2,2,2,2,2,2. That doesn't answer the question.

However a correct approach would look something like this:

`for value in list, print value times 2`

the output of this would be 2,4,6,8,10, etc.... 

hopefully this gives you an idea of what you can change in your code.

**Comment by maryammahjoob** [comment]
oh! I understand what you mean by this and why the code is going wrong as the code doesn't allow the subdirectory to change per loop.  Thank you for the thorough explanation - I really appreciate it, and the practical example really helps me see things clearer! 

Understanding this now, my new code is the following (included cd command): 

`DIR=$(ls); for D in $DIR; do cd $D; var=$(find -type f -name *.txt | wc -l); if [ $var = 0 ]; then echo "$D missing note file"; else echo "$D is not missing note file"; fi; cd ..; done` 

This is allowing the changing of the sub directory for each loop. Unfortunately I am still not seeing what the issue could be. Also, why is it looking through "0, 0] and 0]]" as these are not defined by the variable DIR?

This is the output: `-bash: cd: 0: Not a directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
0 missing note file
-bash: cd: 0]: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
0] missing note file
-bash: cd: 0]]: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
0]] missing note file
-bash: cd: 20180204-01: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180204-01 missing note file
-bash: cd: 20180220-01: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180220-01 missing note file
-bash: cd: 20180220-02: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180220-02 missing note file
-bash: cd: 20180310-01: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180310-01 missing note file
-bash: cd: 20180310-02: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180310-02 missing note file
-bash: cd: 20180405-01: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180405-01 missing note file
-bash: cd: 20180511-01: No such file or directory
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
20180511-01 missing note file`

**Comment by RayNele** [comment]
do a quick `ls` as it seems you have a nonsense directory called `0`. Remove those

**Comment by maryammahjoob** [comment]
oh - you are right! My bad - I deleted those unexpected 0 files now and ran the same code again inserting a `.` after `find` such like this `DIR=$(ls); for D in $DIR; do cd $D; var=$(find . -type f -name *.txt | wc -l); if [ $var = 0 ]; then echo "$D missing note file"; else echo "$D is not missing note file"; fi; cd ..; done` and the code works now! Although I do not understand why the `.` is necessary in this case... 

Thank you for all your help!

**Comment by RayNele** [comment]
`.` just specifies the current working directory. Find by default looks in the current directory so it's kind of redundant.
