### ISSUE TITLE
A2Q1 Unable to Understand Error using 'find' Command

### ISSUE THREAD

**Issue by pdmchang** [BME1478H/Fall2020class#281]
Hello,

My question is in regards to Question 1 of Assignment 2. My approach has been to create two separate directories in the assignment-data folder called "IMAGES" and "DATA_ANALYSIS". I then proceeded to use the 'find' command to select all .jpg files in the assignment-data to move them into the IMAGES directory. However, while my Bash terminal does not report any errors or comments after running the code below, the .jpg files are not copied to the IMAGES directory:

`find . -name '*.jpg' -exec cp {} ~/IMAGES \;`

My operating system is Windows 10. Thank you very much!

Patrick

**Comment by mmaryam2020** [comment]
Hi Patric, 

I think the problem is with giving the path of the IMAGES folder to the command. use ./IMAGES instead of ~/IMAGES to see if it works.

**Comment by pdmchang** [comment]
Hi Maryam, thank you so much! This resolved my issue and the code is working as intended now.
