### ISSUE TITLE
A2Q3 Unable to Identify Syntax Error

### ISSUE THREAD

**Issue by pdmchang** [BME1478H/Fall2020class#282]
Hello,

My question is in regards to Question 3 of Assignment 2. My approach has been to use the loop developed in Question 2 and add a for loop to perform the mv command to change the name of the .txt files in the folders into 'notes.txt'. I was wondering if:

1) The provided code below makes sense and if I'm on the right direction; and
2) The exact syntax error that is occuring.

```
dirctry=$(ls);
   for folder in $dirctry;
      do cd $folder;
      var=$(find . -type f -name '*.txt' | wc -l);
      if [ $var = 0 ];
         then echo "$folder is missing a note file!";
         else for file in *.txt
            do mv $file notes.txt;
         done;
      fi;
  cd ..;
done
```

After running the above code, my Bash terminal reports: "bash: syntax error near unexpected token 'done'. I have tried removing the ';' from both 'done's in the code but the terminal then reports other syntax errors (either near the 'fi' or 'else' parts). 

My operating system is Windows 10. I would appreciate any guidance and thank you very much!

Patrick

**Comment by RayNele** [comment]
Away from a computer but at first glance, `for file in *.txt` seems like an error since `*.txt` does not list all text files it's just a glob.

There may be another error in there that I'm missing I'll return to this later if it is still unsolved.

**Comment by pdmchang** [comment]
Hi Ryan, thanks for the quick reply. Wouldn't using the *.txt as a glob extension essentially identify all files named .txt in the folder? I may have misinterpreted the information provided here https://stackoverflow.com/questions/50173113/loop-through-all-the-files-with-txt-extension-in-bash. 

But since there is only a maximum of one .txt file for each folder, I was struggling previously to write the correct syntax for the specific file per data folder to be renamed through the loop. For instance, I'm not sure what to write in the placeholder: `mv [placeholder] notes.txt`, which is why I utilized a loop.

**Comment by RayNele** [comment]
Whoops sorry it seems you are correct. Anyways I tested your code and it works for me... 

![image](https://user-images.githubusercontent.com/39201728/94087890-dff18000-fddc-11ea-8b69-8790f582226c.png)

where dir1 is the only directory containing a .txt file

**Comment by pdmchang** [comment]
Hi Ray, the code appears to be working for me now - I was missing a simple ';' at the end of the line `else for file *.txt`. I apologize for missing this simple syntax error and thank you very much for your patience and time.
