### ISSUE TITLE
A2Q1 do we need to preserve the directory structure? 

### ISSUE THREAD

**Issue by maryammahjoob** [BME1478H/Fall2020class#286]
Hello, 

I am a bit confused with the wording of A2Q1. I understand in a previous post one of the TA's mentioned we should preserve the directory structure - however previously I emailed Dr. Garton and he said we should only be copying files into /IMAGES, not the folders, and should look into renaming the files so they don't over write each other. 

So my Q is which method is the correct method in terms of receiving full marks for this assignment because I understand both are valid ways to complete the tasks for Q1?

Thanks in advance!

**Comment by RayNele** [comment]
both are fine

**Comment by maryammahjoob** [comment]
ok thank you so much for your response - this clears things up greatly! Also - what is meant by a "single command?"

**Comment by msaleh93** [comment]
Hi @maryammahjoob, I'm also a student. I asked Dr. Garton and he said that, for the purposes of this question, "single command" can be interpreted as a single line of code.

**Comment by maryammahjoob** [comment]
Hi! Thank you for your response - so does this mean you simply use the ";" to make everyone "one line?"

**Comment by maryammahjoob** [comment]
> Hi @maryammahjoob, I'm also a student. I asked Dr. Garton and he said that, for the purposes of this question, "single command" can be interpreted as a single line of code.

Hi! Thank you for your response - so does this mean you simply use the ";" to make the code "one line?"

**Comment by msaleh93** [comment]
Yes, that was my understanding 👍

**Comment by maryammahjoob** [comment]
> Yes, that was my understanding 👍

great thank you so much :)
