### ISSUE TITLE
Assignment 6: Link not working

### ISSUE THREAD

**Issue by constructor-s** [BME1478H/Fall2020class#351]
Hello course instructors, 

On the [Quercus page for assignment 6 (Fall 2020)](https://q.utoronto.ca/courses/187046/assignments/445611) the [link to `last_first_assignment6.ipynb` (`courses/136149/files/6338481`)](https://q.utoronto.ca/courses/136149/files/6338481/download?wrap=1) is not working (I guess that is from previous years): 

> Download and fill in the code in [last_first_assignment6.ipynb](https://q.utoronto.ca/courses/136149/files/6338481/download?wrap=1) where indicated to complete the assignment...

Links to: 

> Access Denied
> 
> You don't have access to view this resource. 

There is [a file available in the Quercus Files section (`courses/187046/files/9593259`)](https://q.utoronto.ca/courses/187046/files/9593259/download?download_frd=1) which I assume is the correct one?

**Comment by RayNele** [comment]
Hey Bill,

sorry for the late reply, both links work for me so I wasn't able to reproduce your problem. 

![image](https://user-images.githubusercontent.com/39201728/96768586-fe32a780-13ab-11eb-8d24-c7d5cc58537d.png)

should look something like that

**Comment by constructor-s** [comment]
Hi @RayNele ,

Sorry I should be more clear. I was talking about Quercus - if I press on [last_first_assignment6.ipynb](https://q.utoronto.ca/courses/136149/files/6338481/download?wrap=1)

![image](https://user-images.githubusercontent.com/10003477/96797925-06034380-13ce-11eb-9c28-c3a91185da27.png)

I get:

![image](https://user-images.githubusercontent.com/10003477/96798029-0bf92480-13ce-11eb-970d-54855b2f2233.png)

**Comment by RayNele** [comment]
Hey Bill,

just download from the files section of quercus for now. I've let Michael
know about the markdown issue and it should be fixed now.
