### ISSUE TITLE
Assignment 3: Negative values in population_size_noise

### ISSUE THREAD

**Issue by luxingz1** [BME1478H/Fall2020class#38]
Hello, 

In question 1d, I have created population_size_noise function  
polulation_size = N0 * np.exp(r*t)+normal-distribution(0, 250)
and obtained bacterial population size for each time point in t. However, I noticed that I have several outputs that have a population size that is below 0. 
If the bacterial population goes below 0, should we terminate the code or continue to output the population size?

**Comment by RayNele** [comment]
No you should not terminate the code. It is working as intended. 

You are adding a random number from a normally distributed curve with mean 0 and stdev 250 to the population growth, you are bound to run into time periods where the added "noise" is greater than the data itself.

**Comment by constructor-s** [comment]
Reviving the thread for Fall 2020: 

Another approach would be to floor all noisy values at zero so it is more realistic for the population analogy. Should we try to do this or does it really not matter for the assignment?

**Comment by RayNele** [comment]
Given it's not real data and we're just trying to teach you basic coding I think we can leave it at the unrealistic population numbers. 

We're running the code and comparing answers to our answer key so you risk being marked wrong if you add in unnecessary clauses

**Comment by constructor-s** [comment]
> 
> 
> Given it's not real data and we're just trying to teach you basic coding I think we can leave it at the unrealistic population numbers.
> 
> We're running the code and comparing answers to our answer key so you risk being marked wrong if you add in unnecessary clauses

Thanks @RayNele for the reply! 

Speaking of comparing answers to answer key, it seems previously the assignment used `seed` as per https://github.com/BME1478H/Fall2020class/issues/40. So that is no longer required this semester?
