### ISSUE TITLE
A10_Q2D - Clarification on graph differences 

### ISSUE THREAD

**Issue by stefanmladjenovic** [BME1478H/Fall2020class#382]
Hi,
I hope you're doing well. Quick question: do you know why my graph looks different than the one presented #263 here? 

I believe we are using the same data (as seen below):
```python 
# load in data
url = 'https://raw.githubusercontent.com/BME1478H/Winter2020class/master/data/world-data-gapminder.csv'
world_data = pd.read_csv(url)

# subset 2014 for this assignment
world_data_2014 = world_data.loc[world_data['year'] == 2014]
```
Our code is identical:
```python 
sns.lmplot('child_mortality', 'life_expectancy', hue='income_group',  data=world_data_2014)
```
However, our final graphs look different. I noticed that the scale on the x and y axis are different. There are other differences, namely that the graph I produced doesn't have as long of a regression line for the 'High' income_group (red line colour).
![a10_q2png](https://user-images.githubusercontent.com/71162611/99898943-92c24b00-2c73-11eb-9209-ec5217076542.png)

Please let me know when you have a chance if you have any thoughts on why these differences may appear. Also please let me know if you have any suggestions in the case that I prepared my answer incorrectly. 

Thank you,
Stefan

Note: I originally commented in the closed thread so I reopened an issue here for visibility. The original comment is reference below:
_Originally posted by @stefanmladjenovic in https://github.com/BME1478H/Fall2020class/issues/263#issuecomment-731717022_

**Comment by RayNele** [comment]
Your graph is fine. My best guess is that something in ~~the dataset or~~ the sns package has been changed within the past 8 months. 

Probably in sns itself since I can't seem to reproduce the graph in #263

**Comment by stefanmladjenovic** [comment]
> 
> 
> Your graph is fine. My best guess is that something in ~the dataset or~ the sns package has been changed within the past 8 months.
> 
> Probably in sns itself since I can't seem to reproduce the graph in #263

Thank you for getting back to me so fast and for your insight -- I sincerely appreciate it!
Will close thread now. Wishing you the best.

Cheers,
Stefan
